# Generated by Django 5.2.8 on 2025-12-14 14:11

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Описание')),
                ('points', models.IntegerField(default=0, verbose_name='Очки')),
                ('achievement_type', models.CharField(choices=[('gold', 'Золотое'), ('silver', 'Серебряное'), ('bronze', 'Бронзовое'), ('platinum', 'Платиновое')], default='bronze', max_length=20, verbose_name='Тип достижения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['-points', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='Загрузите изображение для вашего профиля', null=True, upload_to=users.models.user_avatar_path, verbose_name='Аватар профиля')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('country', models.CharField(blank=True, default='', help_text='Страна определена автоматически по IP или выбрана вручную', max_length=16, verbose_name='Страна')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP адрес при регистрации/последнем входе', null=True, verbose_name='IP адрес')),
                ('status', models.CharField(blank=True, default='', max_length=200, verbose_name='Статус/звание')),
                ('bio', models.TextField(blank=True, default='', max_length=500, verbose_name='О себе')),
                ('vk_url', models.URLField(blank=True, default='', verbose_name='Ссылка на ВКонтакте')),
                ('telegram_url', models.URLField(blank=True, default='', verbose_name='Ссылка на Telegram')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='Ссылка на Instagram')),
                ('youtube_url', models.URLField(blank=True, default='', verbose_name='Ссылка на YouTube')),
                ('points', models.IntegerField(default=0, verbose_name='Очки')),
                ('achievements_count', models.IntegerField(default=0, verbose_name='Количество достижений')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('rank', models.IntegerField(default=9999, verbose_name='Рейтинг в общем зачете')),
                ('games_played', models.IntegerField(default=0, verbose_name='Сыграно игр')),
                ('quizzes_completed', models.IntegerField(default=0, verbose_name='Пройдено викторин')),
                ('courses_completed', models.IntegerField(default=0, verbose_name='Пройдено курсов')),
                ('total_time_played', models.IntegerField(default=0, verbose_name='Общее время (часы)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('displayed_achievements', models.ManyToManyField(blank=True, help_text='Выберите до 4 достижений для отображения в профиле', related_name='displayed_by_profiles', to='users.achievement', verbose_name='Отображаемые достижения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['-points', 'level', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_profile', models.BooleanField(default=True, verbose_name='Публичный профиль')),
                ('show_statistics', models.BooleanField(default=True, verbose_name='Показывать статистику')),
                ('dark_theme', models.BooleanField(default=False, verbose_name='Темная тема')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='Двухфакторная аутентификация')),
                ('two_factor_code_hash', models.CharField(blank=True, default='', max_length=128, verbose_name='Хэш кода 2FA')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push уведомления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройка пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата получения')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='users.achievement', verbose_name='Достижение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижения пользователей',
                'ordering': ('-awarded_at',),
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
