# Generated by Django 5.2.8 on 2025-12-18 16:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название на русском')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Название на английском')),
                ('image', models.ImageField(upload_to='anime_frames/', verbose_name='Изображение кадра')),
                ('year', models.IntegerField(verbose_name='Год выхода')),
                ('genre', models.CharField(max_length=200, verbose_name='Жанр')),
                ('studio', models.CharField(max_length=100, verbose_name='Студия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('hint', models.TextField(verbose_name='Подсказка')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=10, verbose_name='Сложность')),
                ('characters', models.TextField(help_text='Формат JSON: ["Персонаж 1", "Персонаж 2"]', verbose_name='Персонажи (JSON)')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
                'ordering': ['title_ru'],
            },
        ),
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rounds', models.IntegerField(default=10, verbose_name='Количество раундов')),
                ('time_per_round', models.IntegerField(default=45, verbose_name='Время на раунд (сек)')),
                ('base_points', models.IntegerField(default=100, verbose_name='Базовые очки')),
                ('hint_cost', models.IntegerField(default=60, verbose_name='Стоимость подсказки')),
                ('skip_cost', models.IntegerField(default=30, verbose_name='Стоимость пропуска')),
                ('time_bonus_max', models.IntegerField(default=50, verbose_name='Максимальный бонус за время')),
                ('hint_delay', models.IntegerField(default=10, verbose_name='Задержка автоподсказки (сек)')),
            ],
            options={
                'verbose_name': 'Настройка игры',
                'verbose_name_plural': 'Настройки игры',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True, verbose_name='Ключ сессии')),
                ('score', models.IntegerField(default=0, verbose_name='Очки')),
                ('current_round', models.IntegerField(default=1, verbose_name='Текущий раунд')),
                ('total_rounds', models.IntegerField(default=10, verbose_name='Всего раундов')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Правильные ответы')),
                ('hints_used', models.IntegerField(default=0, verbose_name='Использовано подсказок')),
                ('skips_used', models.IntegerField(default=0, verbose_name='Использовано пропусков')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершена')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(verbose_name='Номер раунда')),
                ('user_answer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответ пользователя')),
                ('is_correct', models.BooleanField(null=True, verbose_name='Правильный ответ')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Заработано очков')),
                ('time_spent', models.IntegerField(default=0, verbose_name='Затраченное время (сек)')),
                ('hint_used', models.BooleanField(default=False, verbose_name='Использована подсказка')),
                ('skipped', models.BooleanField(default=False, verbose_name='Пропущено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.anime', verbose_name='Аниме')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game_app.gamesession', verbose_name='Игровая сессия')),
            ],
            options={
                'verbose_name': 'Раунд игры',
                'verbose_name_plural': 'Раунды игры',
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0, verbose_name='Сыграно игр')),
                ('total_score', models.IntegerField(default=0, verbose_name='Общий счет')),
                ('highest_score', models.IntegerField(default=0, verbose_name='Лучший счет')),
                ('total_correct_answers', models.IntegerField(default=0, verbose_name='Всего правильных ответов')),
                ('total_hints_used', models.IntegerField(default=0, verbose_name='Всего использовано подсказок')),
                ('total_skips_used', models.IntegerField(default=0, verbose_name='Всего использовано пропусков')),
                ('average_accuracy', models.FloatField(default=0, verbose_name='Средняя точность')),
                ('last_played', models.DateTimeField(blank=True, null=True, verbose_name='Последняя игра')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика игрока',
                'verbose_name_plural': 'Статистика игроков',
            },
        ),
    ]
