# Generated by Django 5.2.8 on 2025-12-16 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название викторины')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL идентификатор')),
                ('description', models.TextField(verbose_name='Описание викторины')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=20, verbose_name='Сложность')),
                ('time_limit', models.IntegerField(default=10, verbose_name='Лимит времени на вопрос (секунды)')),
                ('total_questions', models.IntegerField(default=10, verbose_name='Количество вопросов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='anime.anime')),
            ],
            options={
                'verbose_name': 'Викторина',
                'verbose_name_plural': 'Викторины',
            },
        ),
        migrations.CreateModel(
            name='QuizComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='anime.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий к викторине',
                'verbose_name_plural': 'Комментарии к викторинам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='anime.quiz')),
            ],
            options={
                'verbose_name': 'Вопрос викторины',
                'verbose_name_plural': 'Вопросы викторины',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='anime.quizquestion')),
            ],
            options={
                'verbose_name': 'Ответ викторины',
                'verbose_name_plural': 'Ответы викторины',
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Количество правильных ответов')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Всего вопросов')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Процент правильных ответов')),
                ('time_spent', models.IntegerField(default=0, verbose_name='Затраченное время (секунды)')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='anime.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Результат викторины',
                'verbose_name_plural': 'Результаты викторин',
                'ordering': ['-completed_at'],
            },
        ),
    ]
