# Generated by Django 5.2.8 on 2025-12-17 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_quiz_quizcomment_quizquestion_quizanswer_quizresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Объяснение ответа'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='points_earned',
            field=models.IntegerField(default=0, verbose_name='Заработанные очки'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=15, verbose_name='Лимит времени на вопрос (секунды)'),
        ),
        migrations.CreateModel(
            name='AnimeUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_points', models.IntegerField(default=0, verbose_name='Очки за аниме')),
                ('quiz_points', models.IntegerField(default=0, verbose_name='Очки за викторины')),
                ('total_points', models.IntegerField(default=0, verbose_name='Всего очков')),
                ('anime_level', models.IntegerField(default=1, verbose_name='Уровень в аниме')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт')),
                ('achievements', models.JSONField(blank=True, default=list, verbose_name='Достижения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_anime', models.ManyToManyField(blank=True, to='anime.anime', verbose_name='Любимые аниме')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anime_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аниме профиль',
                'verbose_name_plural': 'Аниме профили',
            },
        ),
    ]
