# Generated by Django 5.2.8 on 2025-12-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicresult',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
